# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9880566893285f57ca2c61872c64e80e77a0e7e9a982e7459c65bddc0eda47eabaf883264ecb6b45115889ae4ef2952cc4afba6be3e64a3ae908e205c155bc9

test:
  secret_key_base: 7782e7faa95491bf0f86305aed8f9e3aa065adfb2b67eb6fefd1ef9fd8015b4692643e2282b6d765f7e522688d3ce4fe2faec1366aaa73d1822498bef306dcc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
